services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata: